### PR TITLE
Links and scopes

### PR DESCRIPTION
**Pull request by m-mohr**
Do you think it would make sense to allow security refs also for links?

It may also make sense to split the table and clearly show that the fields can be used in different scopes.

Still a draft as this would incur schema changes, but I wanted to show the anticipated changes first for feedback.

### CODE REVIEW

**Comment by jamesfisher-geo** [comment]
> Do you think it would make sense to allow security refs also for links?

That would let us configure authorization to Items and Collection children in a catalog, right? That would be very useful.

> It may also make sense to split the table and clearly show that the fields can be used in different scopes.

Yup, makes sense.

**Comment by m-mohr** [comment]
Yes, and also other "external" things (tile server, documentation, ...)

**Comment by jamesfisher-geo** [comment]
Would you like to make these changes? I'm happy to make the changes in your fork and merge the PR.

**Comment by m-mohr** [comment]
I won't get to it before the sprint. Feel free to just copy&paste my changes into your workspace and close this PR, or do them in my branch. Whatever is easier for you.

**Comment by jamesfisher-geo** [comment]
Changes made in PR #15. Closing this PR.

**Pull request closed without merging**
